# Generated by Django 5.1.6 on 2025-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('programming', 'Programming'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
