# Generated by Django 5.1.6 on 2025-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_lecture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('programming', 'Programming'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
